sudo: required
services:
  - docker

before_install:
  - docker build -t harora2002/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run harora2002/multi-docker-test npm run test -- --coverage
  
after_success:
  - docker build -t harora2002/multi-client ./client  
  - docker build -t harora2002/multi-nginx ./nginx
  - docker build -t harora2002/multi-server ./server
  - docker build -t harora2002/multi-worker ./worker  
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push harora2002/multi-client
  - docker push harora2002/multi-nginx
  - docker push harora2002/multi-server
  - docker push harora2002/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker-app"
  env: "MultiDockerApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-862613634967"
  bucket_path: "multi-docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  
