sudo: required
services:
  - docker

before_install:
  - docker build -t harora1977/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run harora1977/multi-docker-test npm run test -- --coverage
  
after_success:
  - docker build -t harora1977/multi-client ./client  
  - docker build -t harora1977/multi-nginx ./nginx
  - docker build -t harora1977/multi-server ./server
  - docker build -t harora1977/multi-worker ./worker  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push harora1977/multi-client
  - docker push harora1977/multi-nginx
  - docker push harora1977/multi-server
  - docker push harora1977/multi-worker
